# created by Matt Weede
# 11/8/16
#
# This script defines helper functions for the weighted-tree ind-set script w_tree.py

from pptree import *

def define_example_1():
    r = Node(10, 'r')
    a = Node(5, 'a', r)
    b = Node(8, 'b', r)
    c = Node(4, 'x', a)
    d = Node(4, 'd', a)
    e = Node(9, 'e', a)
    f = Node(3, 'f', b)
    g = Node(11, 'g', b)
    h = Node(2, 'h', d)
    i = Node(7, 'i', d)
    j = Node(8, 'j', g)
    return r

def define_example_2():
    R = Node(25, "R")
    a = Node(1, "a", R)
    b = Node(36, "b", R)
    c = Node(84, "c", b)
    d = Node(53, "d", c)
    e = Node(43, "e", b)
    return R

def define_example_3():
    R = Node(12, 'R')
    a = Node(9, 'a', R)
    b = Node(8, 'b', R)
    c = Node(5, 'c', R)
    d = Node(2, 'd', a)
    e = Node(3, 'e', c)
    f = Node(8, 'f', b)
    g = Node(10, 'g', b)
    h = Node(2, 'h', d)
    i = Node(4, 'i', d)
    j = Node(2, 'j', g)
    k = Node(3, 'k', g)
    l = Node(2, 'l', h)
    m = Node(9, 'm', j)
    n = Node(7, 'n', a)
    o = Node(2, 'o', a)
    p = Node(3, 'p', c)
    q = Node(11, 'q', b)
    r = Node(4, 'r', p)
    s = Node(4, 's', o)
    t = Node(7, 't', s)
    u = Node(3, 'u', t)
    v = Node(2, 'v', t)
    w = Node(1, 'w', q)
    x = Node(2, 'x', l)
    y = Node(1, 'y', k)
    z = Node(13, 'z', w)
    return R

def define_example_4():
    R = Node(102, "R")
    a = Node(36, "a", R)
    b = Node(99, "b", a)
    c = Node(31, "c", R)
    d = Node(15, "d", b)
    e = Node(28, "e", R)
    f = Node(123, "f", c)
    g = Node(22, "g", R)
    h = Node(10, "h", g)
    i = Node(90, "i", a)
    j = Node(108, "j", a)
    k = Node(109, "k", b)
    l = Node(69, "l", R)
    m = Node(20, "m", i)
    n = Node(11, "n", k)
    o = Node(32, "o", h)
    p = Node(103, "p", o)
    q = Node(29, "q", g)
    r = Node(59, "r", R)
    s = Node(100, "s", k)
    t = Node(106, "t", p)
    u = Node(124, "u", b)
    v = Node(94, "v", d)
    w = Node(16, "w", R)
    x = Node(25, "x", e)
    y = Node(22, "y", x)
    z = Node(123, "z", l)
    return R

def define_example_5():
    R = Node(51, "R")
    a = Node(43, "a", R)
    b = Node(60, "b", a)
    c = Node(125, "c", b)
    d = Node(28, "d", b)
    e = Node(11, "e", b)
    f = Node(16, "f", a)
    g = Node(21, "g", d)
    h = Node(27, "h", e)
    i = Node(45, "i", a)
    j = Node(23, "j", c)
    k = Node(11, "k", c)
    l = Node(52, "l", j)
    m = Node(94, "m", R)
    n = Node(74, "n", h)
    o = Node(67, "o", a)
    p = Node(35, "p", e)
    q = Node(119, "q", b)
    r = Node(102, "r", b)
    s = Node(45, "s", e)
    t = Node(16, "t", d)
    u = Node(61, "u", q)
    v = Node(45, "v", t)
    w = Node(0, "w", j)
    x = Node(120, "x", c)
    y = Node(26, "y", m)
    z = Node(34, "z", s)
    return R
